//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsgGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MsgRecipient
    {
        public int id { get; set; }
        public string MsgSubject { get; set; }
        public string CustomerID { get; set; }
        public string CardType { get; set; }
        public string CardNo { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public string MsgText { get; set; }
        public Nullable<System.DateTime> LastImported { get; set; }
    }
}
